package mybatistest.entity;
// Generated 2014-11-19 9:41:30 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * UserActionLog generated by hbm2java
 */
public class UserActionLog  implements java.io.Serializable {


     private String logId;
     private String userId;
     private String actionType;
     private Date actionDate;
     private String actionRemark;

    public UserActionLog() {
    }

	
    public UserActionLog(String logId) {
        this.logId = logId;
    }
    public UserActionLog(String logId, String userId, String actionType, Date actionDate, String actionRemark) {
       this.logId = logId;
       this.userId = userId;
       this.actionType = actionType;
       this.actionDate = actionDate;
       this.actionRemark = actionRemark;
    }
   
    public String getLogId() {
        return this.logId;
    }
    
    public void setLogId(String logId) {
        this.logId = logId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }
    public String getActionRemark() {
        return this.actionRemark;
    }
    
    public void setActionRemark(String actionRemark) {
        this.actionRemark = actionRemark;
    }




}


